name: Add Labels

on:
  pull_request:
  pull_request_review:

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
#         if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            documentation
            changelog
      - name: 'echo'
        run: |
          echo 'state = ${{ github.event.review.state }}'
          echo 'name = ${{ github.event_name }}'
          echo 'action = ${{ github.event.action }}'
