on:
  issues:
    types:
      - edited
      - opened

jobs:
  name: 'Label'
  update_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set label
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'bug'
          remove-labels: 'documentation'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
